--- 
title: "Report para Dezembro de 2018" 
date: '`r format(Sys.time(), "%d, %B, %Y")`'
author: "Paulo Ferreira Naibert and Matheus Torma da Silveira"
output: html_document
#      fig_height: 7 
#      fig_width: 11
--- 

# Preliminares

```{r}
library(dygraphs)
library(knitr)
knitr::opts_chunk$set(fig.height=5, fig.width=9.5) 

wd <- "~/doing-ryzen/macro-report/"
setwd(wd)
getwd()

datafolder <- "./data/"
```

# Inflação

```{r}
ipca <- readRDS(paste0(datafolder, "ipca-mat.rds"))
# head(ipca)
```


```{r, echo=FALSE} 
dygraph(ipca[,-2], main = "IPCA") %>%
    # dySeries('ac12') %>% 
    dyFilledLine('ac12') %>% 
    dyBarSeries('var') %>%
    dyAxis("y", label = "IPCA") %>%
    dyLimit(0, color = "black") %>%
    dyLimit(2.5, color = "red") %>%
    dyLimit(4.5, color = "blue") %>%
    dyLimit(6.5, color = "red") %>%
    # dyEvent("2002-01-1", "Lula", labelLoc = "top") %>%
    dyEvent("2008-10-1", "Crise ", labelLoc = "top") %>%
    dyEvent("2010-01-1", "Dilma ", labelLoc = "top") %>%
    dyEvent("2016-09-1", "Temer ", labelLoc = "top") %>%
    dyOptions(axisTickSize = 5)

```

# PIB

```{r}
pib  <- readRDS(paste0(datafolder, "pib-list.rds"))
```

```{r}
# grafico ret pib trim 
dygraph(pib$ret.q, main = "PIB ") %>%
    dySeries(label = "Var ac Ano") %>%
    dyAxis("y", label = "PIB") %>%
    dyLimit(0, color = "black") %>%
    dyEvent("2002-01-1", "Lula", labelLoc = "bottom") %>%
    dyEvent("2008-10-1", "Crise", labelLoc = "bottom") %>%
    dyEvent("2010-01-1", "Dilma", labelLoc = "bottom") %>%
    dyEvent("2016-09-1", "Temer", labelLoc = "bottom") %>%
    dyOptions(includeZero = TRUE)
```
    
```{r}
# grafico ret pib ac 4q
dygraph(pib$ret.y, main = "PIB AC 4q") %>%
    dySeries(label = "Var ac Ano") %>%
    dyAxis("y", label = "PIB") %>%
    dyLimit(0, color = "black") %>%
    dyEvent("2002-01-1", "Lula", labelLoc = "bottom") %>%
    dyEvent("2008-10-1", "Crise", labelLoc = "bottom") %>%
    dyEvent("2010-01-1", "Dilma", labelLoc = "bottom") %>%
    dyEvent("2016-09-1", "Temer", labelLoc = "bottom") %>%
    dyOptions(includeZero = TRUE)
```


```{r}
# grafico pib ac 4q
dygraph(pib$y, main = "PIB AC 4q") %>%
    dySeries(label = "Var ac Ano") %>%
    dyAxis("y", label = "PIB") %>%
    dyLimit(0, color = "black") %>%
    dyEvent("2002-01-1", "Lula", labelLoc = "bottom") %>%
    dyEvent("2008-10-1", "Crise", labelLoc = "bottom") %>%
    dyEvent("2010-01-1", "Dilma", labelLoc = "bottom") %>%
    dyEvent("2016-09-1", "Temer", labelLoc = "bottom") %>%
    dyOptions(includeZero = TRUE)
```

